### ISSUE TITLE
Incomplete Uninstall Program List

### ISSUE THREAD

**Issue by blueelvis** [iangcarroll/cscan#18]
Hi ^_^,

It appears that the list of the programs installed on the system is uncomplete. When I ran CScan, I got 88 lines of tools installed on my system. When I ran BSODInspector (creation of my own :O ) , I got around 460 entries in the list.

On checking further, I see that we are not checking this key (For 32bit programs) - `HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall`

**Comment by blueelvis** [comment]
Working on this right now :)

**Comment by Aurakal** [comment]
Be careful with this key, since it also lists installed updates (KB), so you need to filter them out (same with 64-bit).

**Comment by blueelvis** [comment]
@Aurakal - Yes, it also lists the Windows Updates but the code does not count them. The format in which the Windows Updates are listed is different (I checked this on Windows 10 ) -

![screenshot 45](https://cloud.githubusercontent.com/assets/6985763/17272249/fa08e552-56ae-11e6-9fd4-4f1b61482a0a.png)


Also, are you the same Aura I know on BC? o.O

**Comment by Aurakal** [comment]
That's good. Just wanted to make sure you knew!

And yeah I am. I might not look like it, but I'm Certly's CEO after all.

**Comment by blueelvis** [comment]
@Aurakal - I did not know that but haven't seen any Windows Updates being listed during the BSODInspector trial. So, I thought that Windows Updates are listed elsewhere xD

Great to see you here Aura. Sorry to hear that you are *not* smart xD

**Comment by iangcarroll** [comment]
Should be resolved with the RegistryWrapper class.
