### ISSUE TITLE
Update components to use RegistryWrapper

### ISSUE THREAD

**Issue by blueelvis** [iangcarroll/cscan#21]
We need to change the registry traversal for both the architecture.

From fawo - https://msdn.microsoft.com/en-us/library/microsoft.win32.registryview(v=vs.110).aspx

**Comment by blueelvis** [comment]
The different registry views are only available for HKEY_LOCAL_MACHINE.

**Comment by iangcarroll** [comment]
`RegistryWrapper` is now available which will take care of this (c607a9bb39f758cd610fe8f0b389d60d9fee3c66).
