### ISSUE TITLE
Add a "Collect" command

### ISSUE THREAD

**Issue by Aurakal** [iangcarroll/cscan#23]
Add a "Collect" command like ComboFix and/or FRST. I know you didn't implement the fixes yet, but I just thought I would outline it since it'll be useful for when will come the time to collect samples.

Also, just so you don't introduce the same bug as FRST, if two files are moved in the .zip folder and have the same name, you need to rename one. 

Personally, I see it that way: 

The Collect command will move the files in a .zip archive, and rename them to their MD5 (or SHA1) hash. A .txt file will be created in that archive that will contain the original path + filename of the file, and it's associated MD5/SHA1 for easy organization purpose.

What do you think?

**Comment by iangcarroll** [comment]
Files are saved in the ZIP as `SHA-256 Hash - Original Name`.
